### ISSUE TITLE
Exception thrown from GrowlOptions's setType() method.

### ISSUE THREAD

**Issue by legendwan** [gwtbootstrap3/gwtbootstrap3-extras#145]
I am using extras release 0.9. When I call like this:
GrowlOptions go = new GrowlOptions();
go.setType(GrowlType.SUCCESS);

the setType method throw exception:
13:00:59.907 [ERROR] [ac] Uncaught exception escaped
com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (null) @org.gwtbootstrap3.extras.growl.client.ui.GrowlOptions::setType(Ljava/lang/String;)([string: 'success']): null
    at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:129)
    at com.google.gwt.user.client.ui.Widget.fireEvent(Widget.java:129)
    at com.google.gwt.event.dom.client.DomEvent.fireNativeEvent(DomEvent.java:125)
    at com.google.gwt.user.client.ui.Widget.onBrowserEvent(Widget.java:177)
    at org.gwtbootstrap3.client.ui.Anchor.onBrowserEvent(Anchor.java:530)
    at com.google.gwt.user.client.DOM.dispatchEventImpl(DOM.java:1480)
    at com.google.gwt.user.client.DOM.dispatchEvent(DOM.java:1419)
    at com.google.gwt.user.client.impl.DOMImplStandard.dispatchEvent(DOMImplStandard.java:317)

**Comment by legendwan** [comment]
I wonder how did it work in the demo application?

**Comment by crevete** [comment]
@legendwan I'm just curious because it's always work for me. Can you please provide more details ?

**Comment by legendwan** [comment]
Just these two simple calls.
        GrowlOptions go = new GrowlOptions();
        go.setType(GrowlType.SUCCESS);

In GWT development mode, it outputs:

16:58:15.289 [ERROR] [ac] Uncaught exception escaped

com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (null) @org.gwtbootstrap3.extras.growl.client.ui.GrowlOptions::setType(Ljava/lang/String;)([string: 'success']): null
    at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:129)
    at com.google.gwt.user.client.ui.Widget.fireEvent(Widget.java:129)
    at com.google.gwt.event.dom.client.DomEvent.fireNativeEvent(DomEvent.java:125)
    at com.google.gwt.user.client.ui.Widget.onBrowserEvent(Widget.java:177)
    at com.google.gwt.user.client.DOM.dispatchEventImpl(DOM.java:1480)
    at com.google.gwt.user.client.DOM.dispatchEvent(DOM.java:1419)
    at com.google.gwt.user.client.impl.DOMImplStandard.dispatchEvent(DOMImplStandard.java:317)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:341)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:222)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:137)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:589)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:293)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:299)
    at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:296)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:551)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368)
    at java.lang.Thread.run(Thread.java:744)
Caused by: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: (null) @org.gwtbootstrap3.extras.growl.client.ui.GrowlOptions::setType(Ljava/lang/String;)([string: 'success']): null
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:203)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:88)
    at com.google.gwt.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:52)
    at com.siemens.plm.bitools.analytics.ac.gwt.client.pages.home.HomeActivity.goToServersPage(HomeActivity.java:51)
    at com.siemens.plm.bitools.analytics.ac.gwt.client.pages.home.HomeViewImpl.onServersClick(HomeViewImpl.java:50)
    at com.siemens.plm.bitools.analytics.ac.gwt.client.pages.home.HomeViewImpl_HomeViewImplUiBinderImpl$Widgets$3.onClick(HomeViewImpl_HomeViewImplUiBinderImpl.java:73)
    at com.google.gwt.event.dom.client.ClickEvent.dispatch(ClickEvent.java:56)
    at com.google.gwt.event.dom.client.ClickEvent.dispatch(ClickEvent.java:1)
    at com.google.gwt.event.shared.GwtEvent.dispatch(GwtEvent.java:1)
    at com.google.web.bindery.event.shared.EventBus.dispatchEvent(EventBus.java:40)
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:193)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:88)
    at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:127)
    at com.google.gwt.user.client.ui.Widget.fireEvent(Widget.java:129)
    at com.google.gwt.event.dom.client.DomEvent.fireNativeEvent(DomEvent.java:125)
    at com.google.gwt.user.client.ui.Widget.onBrowserEvent(Widget.java:177)
    at com.google.gwt.user.client.DOM.dispatchEventImpl(DOM.java:1480)
    at com.google.gwt.user.client.DOM.dispatchEvent(DOM.java:1419)
    at com.google.gwt.user.client.impl.DOMImplStandard.dispatchEvent(DOMImplStandard.java:317)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:341)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:222)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:137)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:589)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:293)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:299)
    at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:296)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:551)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368)
    at java.lang.Thread.run(Thread.java:744)
Caused by: com.google.gwt.core.client.JavaScriptException: (null) @org.gwtbootstrap3.extras.growl.client.ui.GrowlOptions::setType(Ljava/lang/String;)([string: 'success']): null
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:252)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:137)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:589)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeVoid(ModuleSpace.java:315)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeVoid(JavaScriptHost.java:107)
    at org.gwtbootstrap3.extras.growl.client.ui.GrowlOptions.setType(GrowlOptions.java)
    at org.gwtbootstrap3.extras.growl.client.ui.GrowlOptions.setType(GrowlOptions.java:238)
    at com.siemens.plm.bitools.analytics.ac.gwt.client.ClientUtils.showStatus(ClientUtils.java:27)
    at com.siemens.plm.bitools.analytics.ac.gwt.client.AdministrativeConsole.onMenuSelection(AdministrativeConsole.java:222)
    at com.siemens.plm.bitools.analytics.ac.gwt.client.events.MenuSelectionEvent.dispatch(MenuSelectionEvent.java:38)
    at com.siemens.plm.bitools.analytics.ac.gwt.client.events.MenuSelectionEvent.dispatch(MenuSelectionEvent.java:1)
    at com.google.gwt.event.shared.GwtEvent.dispatch(GwtEvent.java:1)
    at com.google.web.bindery.event.shared.EventBus.dispatchEvent(EventBus.java:40)
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:193)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:88)
    at com.google.gwt.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:52)
    at com.siemens.plm.bitools.analytics.ac.gwt.client.pages.home.HomeActivity.goToServersPage(HomeActivity.java:51)
    at com.siemens.plm.bitools.analytics.ac.gwt.client.pages.home.HomeViewImpl.onServersClick(HomeViewImpl.java:50)
    at com.siemens.plm.bitools.analytics.ac.gwt.client.pages.home.HomeViewImpl_HomeViewImplUiBinderImpl$Widgets$3.onClick(HomeViewImpl_HomeViewImplUiBinderImpl.java:73)
    at com.google.gwt.event.dom.client.ClickEvent.dispatch(ClickEvent.java:56)
    at com.google.gwt.event.dom.client.ClickEvent.dispatch(ClickEvent.java:1)
    at com.google.gwt.event.shared.GwtEvent.dispatch(GwtEvent.java:1)
    at com.google.web.bindery.event.shared.EventBus.dispatchEvent(EventBus.java:40)
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:193)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:88)
    at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:127)
    at com.google.gwt.user.client.ui.Widget.fireEvent(Widget.java:129)
    at com.google.gwt.event.dom.client.DomEvent.fireNativeEvent(DomEvent.java:125)
    at com.google.gwt.user.client.ui.Widget.onBrowserEvent(Widget.java:177)
    at com.google.gwt.user.client.DOM.dispatchEventImpl(DOM.java:1480)
    at com.google.gwt.user.client.DOM.dispatchEvent(DOM.java:1419)
    at com.google.gwt.user.client.impl.DOMImplStandard.dispatchEvent(DOMImplStandard.java:317)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:341)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:222)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:137)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:589)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:293)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:299)
    at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:296)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:551)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368)
    at java.lang.Thread.run(Thread.java:744)

**Comment by legendwan** [comment]
For now, I have to use it like this:

        GrowlType gt = GrowlType.INFO;

        switch (type) {
            case SUCCESS:
                gt = GrowlType.SUCCESS;
                break;
            case ERROR:
                gt = GrowlType.DANGER;
                break;
            case WARNING:
                gt = GrowlType.WARNING;
                break;
            case INFO:
                gt = GrowlType.INFO;
            default:
                break;
        }

        Growl.growl(status, gt);

**Comment by crevete** [comment]
@legendwan I think it's due to the GWT classic dev mode. Because the GrowlOption class does not extend JavaScriptObject, that causes this issue on runtime. I was surprised this works fine for me, it's just because I always use Super Dev Mode I guess, once compiled, this always works. The workaround would be to make GrowlOption extend JavaScriptObject and provide a static accessor like this:

```
public class GrowlOption extends JavaScriptObject {
    protected GrowlOption() {}
    public static GrowlOption newOption {
        return JavaScriptObject.newObject().cast();
    }
    ...
}
```

Or you can try the new Bootstrap Notify (Growl 3.0.0) I've just wrapped in 1.0-SNAPSHOT.

**Comment by crevete** [comment]
@jgodi  I think this could be closed, since Growl 2.0.1 is now obsolete and Notify works fine. And I would better to remove Growl from the extra project and the demo page

**Comment by jgodi** [comment]
Works for me, I will make an issue to remove Growl before the 1.0 release. Thanks!

**Comment by worknperk** [comment]
We should mark the Growl library as "Deprecated".
