### ISSUE TITLE
No Class matching Slider

### ISSUE THREAD

**Issue by soodrah** [gwtbootstrap3/gwtbootstrap3-extras#299]
In my gwt.xml I have included the gwtBootstrap as follows
`  <inherits name="org.gwtbootstrap3.GwtBootstrap3NoTheme"/>
     
     <inherits name="org.gwtbootstrap3.extras.slider.Slider"/>` 

In my Ui.xml i am importing the slider as follows
`<ui:UiBinder xmlns:ui="urn:ui:com.google.gwt.uibinder"
	xmlns:g="urn:import:com.google.gwt.user.client.ui"
	xmlns:b3="urn:import:org.gwtbootstrap3.extras.slider.client.ui"
	xmlns:b="urn:import:org.gwtbootstrap3.client.ui">`

I am trying to lay out the slider as a test as follows inside a docklayoutPanel

          			<g:north size="50">
          			<g:HTMLPanel addStyleNames="{style.southInputPanel}">
          			
          			
  
          			<b3:Slider ui:field="mySlider" min="0" max="20" step="1" value="14"/>
          			
          			</g:HTMLPanel>
          			</g:north>
          			
          			
          			
          			<g:south size="50">
          			<g:HTMLPanel addStyleNames="{style.southInputPanel}">
          			
          			<g:Label>This is the South panel</g:Label>
          			</g:HTMLPanel>
          			
          			</g:south>

When i launch my app I get the following error, what am i doing wrong ?

[DEBUG] [usingthedocklayoutpanel] - Rebinding com.strategyPerspective.client.MyDockLayoutPanel.MyDockLayoutPanelUiBinder
	[DEBUG] [usingthedocklayoutpanel] - Invoking generator com.google.gwt.uibinder.rebind.UiBinderGenerator
		[ERROR] [usingthedocklayoutpanel] - No class matching "Slider" in urn:import:org.gwtbootstrap3.extras.slider.client.ui: <b3:Slider max='20' min='0' step='1' ui:field='mySlider' value='14'> (:398)
[ERROR] [usingthedocklayoutpanel] - Deferred binding failed for 'com.strategyPerspective.client.MyDockLayoutPanel.MyDockLayoutPanelUiBinder'; expect subsequent failures
[ERROR] [usingthedocklayoutpanel] - Unable to load module entry point class com.strategyPerspective.client.UsingTheDockLayoutPanel (see associated exception for details)
[ERROR] [usingthedocklayoutpanel] - Failed to load module 'usingthedocklayoutpanel' from user agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:24.0) Gecko/20100101 Firefox/24.0' at localhost:61325

**Comment by crevete** [comment]
Your code looks good. Would you please provide your ui.xml? Or fork https://github.com/gwtbootstrap3/gwtbootstrap3-seed and then creating a view that showcases the problem.

**Comment by soodrah** [comment]
Hi Crevete
Attaching my ui.xml, I am also trying to debug if its a classloading issue, will take some time for me to debug that, will run the seed project later, meanwhile here is my ui.xml,thanks for looking into this. 
[MyDockLayoutPanel.ui.xml.zip](https://github.com/gwtbootstrap3/gwtbootstrap3-extras/files/208240/MyDockLayoutPanel.ui.xml.zip)

**Comment by crevete** [comment]
I've tried this ui.xml, it works fine. The error message is clear: there is no Slider class in your classpath. Maybe you place the gwt.xml file at the wrong place. Please fork the seed project.

**Comment by soodrah** [comment]
sure will do that... When you say fork the seed project, do you want me to replace the UI in it with my UI, Please let me know. My gwt.xml is in the right place, since it was working before I made this change and if I remove this change it still works fine. I will share that too with you and look into classloading issues.

**Comment by soodrah** [comment]
Including the changes I made to the seed project and also the log. The project runs fine after changes but i see a blank page.
[seedWebapp.txt](https://github.com/gwtbootstrap3/gwtbootstrap3-extras/files/209496/seedWebapp.txt)
[toshare.zip](https://github.com/gwtbootstrap3/gwtbootstrap3-extras/files/209497/toshare.zip)

**Comment by soodrah** [comment]
For now also including the verbose output of the classloader, it seems to find the SliderEntryPoint but not sure why not the Slider
[Console.txt](https://github.com/gwtbootstrap3/gwtbootstrap3-extras/files/209552/Console.txt)

**Comment by crevete** [comment]
When I say "fork" the project, I mean you go https://github.com/gwtbootstrap3/gwtbootstrap3-seed then click "fork" to fork it in your account, then try to demonstrate the issue. By this way, I can access to your project to see what's wrong. The logs files you've shared do not help a lot...

**Comment by soodrah** [comment]
Hi Crevete
Instead of forking the seed project, I added my full sample project to my clone. This probably will help...Please let me know. Here is the url

https://github.com/soodrah/DockLayoutSample

**Comment by soodrah** [comment]
https://github.com/soodrah/DockLayoutSample.git

**Comment by crevete** [comment]
Your project works fine. I checked again the Console.txt, it shows that you are using GWT 2.6 rather than 2.7. I did reproduce your issue when switching with GWT 2.6. Next time, please ensure your environment is correctly configured than make an issue report.

**Comment by soodrah** [comment]
hi Crevete
I have updated the project as suggested by you. The slider error is now gone but now I am getting a different error, Could you please help me understand what i missed. I have pushed my changes to Github
1:44:18.105 [ERROR] [usingthedocklayoutpanel] Member &#39;fireSlideEvent(Ljava/lang/Double;)&#39; in JSNI reference &#39;@org.gwtbootstrap3.extras.slider.client.ui.base.SliderBase::fireSlideEvent(Ljava/lang/Double;)&#39; could not be found; expect subsequent failures

java.lang.NoSuchFieldError: fireSlideEvent(Ljava/lang/Double;)
    at com.google.gwt.dev.shell.CompilingClassLoader$DispatchClassInfoOracle.getDispId(CompilingClassLoader.java:173)
    at com.google.gwt.dev.shell.CompilingClassLoader.getDispId(CompilingClassLoader.java:1043)
    at com.google.gwt.dev.shell.Jsni$JsSourceGenWithJsniIdentFixup.visit(Jsni.java:170)
    at com.google.gwt.dev.js.ast.JsInvocation.traverse(JsInvocation.java:91)
    at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
    at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:444)
    at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
    at com.google.gwt.dev.js.JsToStringGenerationVisitor.visit(JsToStringGenerationVisitor.java:445)
    at com.google.gwt.dev.js.ast.JsExprStmt.traverse(JsExprStmt.java:41)
    at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
    at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:444)
    at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
    at com.google.gwt.dev.js.JsToStringGenerationVisitor.printJsBlock(JsToStringGenerationVisitor.java:961)
    at com.google.gwt.dev.js.JsSourceGenerationVisitor.visit(JsSourceGenerationVisitor.java:59)
    at com.google.gwt.dev.js.ast.JsBlock.traverse(JsBlock.java:52)
    at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
    at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:444)
    at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
    at com.google.gwt.dev.shell.Jsni.generateJavaScriptForHostedMode(Jsni.java:251)
    at com.google.gwt.dev.shell.Jsni.getJavaScriptForHostedMode(Jsni.java:239)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.createNativeMethods(ModuleSpaceOOPHM.java:53)
    at com.google.gwt.dev.shell.CompilingClassLoader.injectJsniMethods(CompilingClassLoader.java:1400)
    at com.google.gwt.dev.shell.CompilingClassLoader.findClass(CompilingClassLoader.java:1170)
    at com.google.gwt.dev.shell.CompilingClassLoader.loadClass(CompilingClassLoader.java:1215)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.strategyPerspective.client.MyDockLayoutPanel_MyDockLayoutPanelUiBinderImpl.createAndBindUi(MyDockLayoutPanel_MyDockLayoutPanelUiBinderImpl.java:55)
    at com.strategyPerspective.client.MyDockLayoutPanel_MyDockLayoutPanelUiBinderImpl.createAndBindUi(MyDockLayoutPanel_MyDockLayoutPanelUiBinderImpl.java:1)
    at com.strategyPerspective.client.MyDockLayoutPanel.&lt;init&gt;(MyDockLayoutPanel.java:45)
    at com.strategyPerspective.client.UsingTheDockLayoutPanel.onModuleLoad(UsingTheDockLayoutPanel.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:423)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:530)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368)
    at java.lang.Thread.run(Thread.java:745)

Please let me know if you need anything else. Do you need me to create a new issue
https://github.com/soodrah/DockLayoutSample.git
