### ISSUE TITLE
FireSlideEvent in JSNI reference @org.gwtbootstrap3.extras.slider.client.ui.base.SliderBase could not be found

### ISSUE THREAD

**Issue by soodrah** [gwtbootstrap3/gwtbootstrap3-extras#301]
hi Crevete
I have updated the project as suggested by you. The slider error is now gone but now I am getting a different error, Could you please help me understand what i missed. I have pushed my changes to Github
1:44:18.105 [ERROR] [usingthedocklayoutpanel] Member &#39;fireSlideEvent(Ljava/lang/Double;)&#39; in JSNI reference &#39;@org.gwtbootstrap3.extras.slider.client.ui.base.SliderBase::fireSlideEvent(Ljava/lang/Double;)&#39; could not be found; expect subsequent failures

java.lang.NoSuchFieldError: fireSlideEvent(Ljava/lang/Double;)
    at com.google.gwt.dev.shell.CompilingClassLoader$DispatchClassInfoOracle.getDispId(CompilingClassLoader.java:173)
    at com.google.gwt.dev.shell.CompilingClassLoader.getDispId(CompilingClassLoader.java:1043)
    at com.google.gwt.dev.shell.Jsni$JsSourceGenWithJsniIdentFixup.visit(Jsni.java:170)
    at com.google.gwt.dev.js.ast.JsInvocation.traverse(JsInvocation.java:91)
    at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
    at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:444)
    at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
    at com.google.gwt.dev.js.JsToStringGenerationVisitor.visit(JsToStringGenerationVisitor.java:445)
    at com.google.gwt.dev.js.ast.JsExprStmt.traverse(JsExprStmt.java:41)
    at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
    at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:444)
    at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
    at com.google.gwt.dev.js.JsToStringGenerationVisitor.printJsBlock(JsToStringGenerationVisitor.java:961)
    at com.google.gwt.dev.js.JsSourceGenerationVisitor.visit(JsSourceGenerationVisitor.java:59)
    at com.google.gwt.dev.js.ast.JsBlock.traverse(JsBlock.java:52)
    at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
    at com.google.gwt.dev.js.ast.JsVisitor.doAccept(JsVisitor.java:444)
    at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
    at com.google.gwt.dev.shell.Jsni.generateJavaScriptForHostedMode(Jsni.java:251)
    at com.google.gwt.dev.shell.Jsni.getJavaScriptForHostedMode(Jsni.java:239)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.createNativeMethods(ModuleSpaceOOPHM.java:53)
    at com.google.gwt.dev.shell.CompilingClassLoader.injectJsniMethods(CompilingClassLoader.java:1400)
    at com.google.gwt.dev.shell.CompilingClassLoader.findClass(CompilingClassLoader.java:1170)
    at com.google.gwt.dev.shell.CompilingClassLoader.loadClass(CompilingClassLoader.java:1215)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.strategyPerspective.client.MyDockLayoutPanel_MyDockLayoutPanelUiBinderImpl.createAndBindUi(MyDockLayoutPanel_MyDockLayoutPanelUiBinderImpl.java:55)
    at com.strategyPerspective.client.MyDockLayoutPanel_MyDockLayoutPanelUiBinderImpl.createAndBindUi(MyDockLayoutPanel_MyDockLayoutPanelUiBinderImpl.java:1)
    at com.strategyPerspective.client.MyDockLayoutPanel.&lt;init&gt;(MyDockLayoutPanel.java:45)
    at com.strategyPerspective.client.UsingTheDockLayoutPanel.onModuleLoad(UsingTheDockLayoutPanel.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:423)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:530)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368)
    at java.lang.Thread.run(Thread.java:745)

Please let me know if you need anything else. I created a new issue since was not sure if you would look at the previous one since its labeled as invalid.
https://github.com/soodrah/DockLayoutSample.git

Also pasting my  classpath to show that i am using gwt 2.7.0 now

`<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="src" output="test-classes" path="test"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="lib" path="GWT-HighCharts/org.moxieapps.gwt.highcharts-1.7.0.jar" sourcepath="GWT-HighCharts/org.moxieapps.gwt.highcharts-1.7.0-sources.jar"/>
	<classpathentry kind="lib" path="GWTQuery/gwtquery-1.4.3.jar" sourcepath="GWTQuery/gwtquery-1.4.3-sources.jar"/>
	<classpathentry kind="lib" path="gwtBootstrapDemo/gwtbootstrap3-1.0-SNAPSHOT.jar"/>
	<classpathentry kind="lib" path="gwtBootstrapDemo/gwtbootstrap3-extras-1.0-SNAPSHOT.jar"/>
	<classpathentry kind="con" path="com.google.gwt.eclipse.core.GWT_CONTAINER/GWT (2)"/>
	<classpathentry kind="output" path="war/WEB-INF/classes"/>
</classpath>`

**Comment by crevete** [comment]
One more time, your project works good, I can see the slider. I really don't know how you can get ```java.lang.NoSuchFieldError```. (Not an Exception, but an Error). It's certainly an environment configuration issue. I'm sorry and not be able to help you... FYI, I'm running your project under Eclipse Mars, Google Plugin for Eclipse 4.4/4.5	3.9.0.v20160321-2025, GWT 2.7, JRE 7 or 8.

**Comment by soodrah** [comment]
Few more questions - 
1. What is SDM ?
2. Can you share the program arguments and VM arguments with me ?
Here is what I am using 
Program Arguments
-nosuperDevMode -startupUrl UsingTheDockLayoutPanel.html -war /Users/rahulsood/Data/sandbox/DockLayoutPanelSample/UsingTheDockLayoutPanel/war -remoteUI "${gwt_remote_ui_server_port}:${unique_id}" -logLevel INFO -codeServerPort 9997 -port 8888 com.strategyPerspective.UsingTheDockLayoutPanel com.strategyPerspective.UsingTheDockLayoutPanel
Vm arguments
-XstartOnFirstThread -Xmx1024m -verbose:class

I understand that it is env configuration, the more you share your configuration, it will help me and save my time, appreciate it thanks

**Comment by crevete** [comment]
SDM = Super Dev Mode http://www.gwtproject.org/articles/superdevmode.html
I'm using the same configuration, but on SDM. Please remove ```-nosuperDevMode```. Classic dev mode is being obsolete.

**Comment by crevete** [comment]
@soodrah without your reply, I will close this issue.

**Comment by soodrah** [comment]
hi Crevete
Sorry for the late reply. I did get it working. I was experimenting with the various maven goals to make sure those work. And all that is working too. Thanks for your help.

**Comment by crevete** [comment]
Cool!
